/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://3m64bflu7nbkzffysyanilzk5e.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-zyf7cleg2ncxtbdi3ek2hwigcy",
    "aws_cognito_identity_pool_id": "us-east-1:dc81723d-5480-4d65-bcc1-aff12e354286",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_KRoXPIA2H",
    "aws_user_pools_web_client_id": "1232qtam8f0qb0lmj2katpbte9",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS",
            "REQUIRES_UPPERCASE"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "toolbelt-storage-bdbe0c92143228-staging",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
